# Generated by Django 6.0.3 on 2026-03-27 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
